CREATE TABLE `schedule` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(191) NOT NULL,
  `start` DATETIME(3) NOT NULL,
  `end` DATETIME(3) NOT NULL,
  `color` VARCHAR(191) NULL DEFAULT '#0F2854',
  `created_by` VARCHAR(191) NULL,
  `create_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `deleted` BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `schedule_upload_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(191) NULL,
  `uploader` VARCHAR(191) NULL,
  `successCount` INTEGER NOT NULL DEFAULT 0,
  `failCount` INTEGER NOT NULL DEFAULT 0,
  `errors` LONGTEXT NULL,
  `create_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
